version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "4000:4000"  # Map container port 3000 to host port 3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
