version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  # Map container port 3000 to host port 3000
    volumes:
      - .:/app  # Mount the app directory for live code reloading (optional)
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
